version: '3.8'

services:
  translation_service:
    build:
      context: ./gpt  # Путь к директории с вашим Flask приложением
    ports:
      - "5000:5000"

  aiogram_bot:
    build:
      context: ./bot  # Путь к директории с вашим Aiogram ботом
    depends_on:
      - translation_service
    env_file:
      - ./bot/.env  # Убедитесь, что файл .env находится в этой директории
