version: '3.8'

services:
  translation_service:
    build:
      context: ./gpt
    ports:
      - "5000:5000"
    networks:
      - my_network

  aiogram_bot:
    build:
      context: ./bot
    depends_on:
      - translation_service
    environment:
      - API_TOKEN=
      - TRANSLATION_SERVICE_URL=http://translation_service:5000/translate
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
